# Generated by Django 2.0.7 on 2018-07-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stuffit', '0002_auto_20180710_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['modified']},
        ),
    ]
