# Generated by Django 2.0.7 on 2018-07-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stuffit', '0003_auto_20180711_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
