# Generated by Django 2.0.7 on 2018-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stuffit', '0004_auto_20180711_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='b',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='node',
            name='g',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='node',
            name='r',
            field=models.FloatField(default=1.0),
        ),
    ]
